# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "九千鸦的博客"
description: > # this means to ignore newlines until "baseurl:"
  Material theme based on <a href="http://materializecss.com">Materialize.css</a> for jekyll sites
baseurl: "" # the subpath of your site, e.g. /blog
# 用于disqus
# for disqus
url: "https://kyakya.icu"  # the base hostname & protocol for your site, e.g. http://example.com



# MatJek 该样式特殊的配置 https://shawnteoh.github.io/matjek
# MatJek specific configurations
github_profile: "https://github.com/caliburn1994"
user: "九千鸦"
user_email: "caliburn1994@gmail.com"
contact_url: "https://twitter.com/caliburn1994"
google_tracking_id: "UA-121898091-1"
google_site_verification: "UA-121898091-1"
disqus_shortname: "jiu-qian-ya-de-bo-ke"

#编码
encoding: UTF-8


# Build settings
# Markdown显示方式、插件
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock

# 资源
# resource
sass:
  style: compressed


# github 仓库地址，用于读取仓库内信息
# 暂时没任何作用
repository: caliburn1994/caliburn1994.github.io


# article
permalink: /:title  # 文章地址 ，url of article  {{url}}/{{title}}
future: true  # 允许日期为未来，allow date is future

# 分页功能
# Pagination Settings v2
pagination:
  enabled: true
  per_page: 5




