name: CI

on:
  push:
    branches:
      - ci/drawio-1
  pull_request:
    branches:
      - ci/drawio-1


jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - run: |
          # https://snapcraft.io/install/drawio/ubuntu
          sudo apt update

          sudo apt -y install curl xvfb nano \
          libgtk-3-0 \
          libnotify4 libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libappindicator3-1 libsecret-1-0 \
          libgbm1 \
          snapd
          
          # Install draw.io
          sudo snap install drawio


      - name: List all changed files and convert drawio files to images
        run: |          
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            xvfb-run -a drawio -x -f png -o "${file}.png" "${file}"
          done
